# only use to override values in application.yaml for running locally
logging:
  level:
    com.hertz.api: DEBUG

com:
  hertz:
    digital:
      msf:
        security:
          jwt:
            enabled: false
            token: unauthenticated
